module.exports = {
  mainSidebar: [
    'index',
    'DocumentationHub',
    'StrategyAndRequirements',
    'FeatureCatalogue',
    'UserStories',
    'SolutionArchitecture',
    'DomainDataApiAndEvents',
    'SecurityReliabilityAndCompliance',
    'DeliveryQualityAndOperations',
    { type: 'category', label: 'Governance & ADRs', items: [{ type: 'autogenerated', dirName: '12-governance-and-decisions' }] }
  ]
};
