module.exports = {
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: '1. Product Vision & Master',
      collapsed: false,
      items: ['restaurant-master']
    },
    {
      type: 'category',
      label: '2. Final Plan',
      items: ['final-plan']
    },
    {
      type: 'category',
      label: '3. Features & Definitions',
      items: ['final-features']
    },
    {
      type: 'category',
      label: '4. User Stories',
      items: ['final-user-stories']
    },
    {
      type: 'category',
      label: '12. Governance & ADRs',
      items: [{ type: 'autogenerated', dirName: '12-governance-and-decisions' }]
    }
  ]
};
