module.exports = {
  mainSidebar: [
    'index',
    {type:'category', label:'1. Product Vision', collapsed:false, items:[{type:'autogenerated', dirName:'01-product-vision'}]},
    {type:'category', label:'2. Product Strategy', items:[{type:'autogenerated', dirName:'02-product-strategy'}]},
    {type:'category', label:'3. Product Requirements', items:[{type:'autogenerated', dirName:'03-product-requirements'}]},
    {type:'category', label:'4. Solution Architecture', items:[{type:'autogenerated', dirName:'04-solution-architecture'}]},
    {type:'category', label:'5. Data & API', items:[{type:'autogenerated', dirName:'05-data-and-api'}]},
    {type:'category', label:'6. AI & Automation', items:[{type:'autogenerated', dirName:'06-ai-and-automation'}]},
    {type:'category', label:'7. Device Integrations', items:[{type:'autogenerated', dirName:'07-device-integrations'}]},
    {type:'category', label:'8. Security', items:[{type:'autogenerated', dirName:'08-security'}]},
    {type:'category', label:'9. DevOps & Deployment', items:[{type:'autogenerated', dirName:'09-devops-and-deployment'}]},
    {type:'category', label:'10. Quality Engineering', items:[{type:'autogenerated', dirName:'10-quality-engineering'}]},
    {type:'category', label:'11. Delivery Roadmap', items:[{type:'autogenerated', dirName:'11-delivery-roadmap'}]},
    {type:'category', label:'12. Governance & ADRs', items:[{type:'autogenerated', dirName:'12-governance-and-decisions'}]}
  ]
};
